name: Debugging Demo

on: 
    workflow_dispatch:
    push:

env:
    USER_1: "foo-user"
    USER_2: "bar-user"

jobs:
    debug_job:
        runs-on: ubuntu-latest
        steps:
        - name: step 1 - checkout Repo
          uses: actions/checkout@v4
        
        - name: step 2 - set USER_1 as USERNAME
          run: |
            echo "USERNAME=$USER_1" >> $GITHUB_ENV

        - name: step 3 - printing USERNAME
          run: |
            echo "printing USERNAME env variable from previous step"
            echo "USERNAME ======= $USERNAME"
            exit 1

        - name: step4 - printing USER_2
          run: |
            echo $USER_2